# Generated by Django 2.2 on 2019-04-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myweb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('jianjie', models.CharField(max_length=255)),
                ('riqi', models.CharField(max_length=255)),
                ('jiage', models.CharField(max_length=255)),
                ('chuabnshe', models.CharField(max_length=255)),
                ('pingfen', models.CharField(max_length=255)),
            ],
        ),
    ]
