# Generated by Django 2.2 on 2019-04-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jingdong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biaoti', models.CharField(max_length=255)),
                ('jiage', models.CharField(max_length=255)),
                ('jianjie', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='myweb',
            new_name='douban',
        ),
    ]
