# Generated by Django 2.2 on 2019-04-25 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190425_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='douban',
            old_name='chuabnshe',
            new_name='chubanshe',
        ),
    ]
